version: "3"
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    volumes:
      - data-volume:/data/db
    networks:
      testing_net:
        ipv4_address: 172.28.2.1
  amqp:
    image: rabbitmq:3-management
    container_name: amqp
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.28.2.2:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      testing_net:
        ipv4_address: 172.28.2.2
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: consumer
    container_name: consumer
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=172.28.2.1
      - MONGODB_PORT=27017
      - MONGODB_BASE=languages
      - AMQP_URI=172.28.2.2
      - AMQP_PORT=5672
    networks:
      testing_net:
        ipv4_address: 172.28.2.3
    depends_on:
      - database
      - amqp
    restart: on-failure
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    image: service
    container_name: service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=172.28.2.1
      - MONGODB_PORT=27017
      - MONGODB_BASE=languages
    networks:
      testing_net:
        ipv4_address: 172.28.2.4
    depends_on:
      - database
    restart: on-failure
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  data-volume:
